import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactLenis } from "lenis/react";
import "./globals.css";
import { saiba, glitchGoblin, ethnocentric, tekoLight, tekoRegular } from "@/src/lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${saiba.variable} ${glitchGoblin.variable} ${ethnocentric.variable} ${tekoLight.variable} ${tekoRegular.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReactLenis root options={{ lerp: 0.1, duration: 1.2, anchors: true }}>
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
